version: "3"

services:

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

  worker:
    build: .
    ports:
      - "9990:9990"
    env_file:
      - .env
    entrypoint: [ python, worker/main.py ]

  redis:
    image: redis:latest
    ports:
      - "8888:8888"

networks:
  default: null
